### ISSUE TITLE
Colin McRae Rally 2005 P3D format

### ISSUE THREAD

**Issue by Fabxx** [wurunduk/blender-p3d-import-export#1]
Does this tool support P3D format from cmr 2005? there are no tools around the web sadly to convert it to 3ds or some other format :(

**Comment by wurunduk** [comment]
No, this tool is made for crashday's .p3d format. As far as i know, this exact format is not used anywhere else.

**Comment by RoadTrain** [comment]
@Fabio-Git-dev There are tools for CMR05, but they are very old: http://www.mediafire.com/file/m14y3kqzohuqqbt/extractiontools.rar/file

Found via https://forum.xentax.com/viewtopic.php?t=13670

Would be cool to preserve them somewhere at GH, e.g.
