### ISSUE TITLE
Problem install addons to blender 2.93.3

### ISSUE THREAD

**Issue by geds3169** [wurunduk/blender-p3d-import-export#2]
Hello, I am having difficulty installing the addon.
I select install then the folder "blender-p3d-import-export-master" then the "__init__.py" and I select "install Add-on", it does not seem to work and I have no error message , I am looking for the addon in the list, it does not appear.

Cordialy

**Comment by wurunduk** [comment]
You don't need to select the init.py. When downloading the plugin from github you should get a zip file which you should select. No need to unzip it.

**Comment by geds3169** [comment]
Ok, thanks for the quick feedback, I'm testing this today. And thanks for the work. Regards
