### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by dorathehonria** [wurunduk/blender-p3d-import-export#3]
<img width="1304" alt="Screen Shot 2022-01-25 at 10 11 57 AM" src="https://user-images.githubusercontent.com/96855623/151035117-74899810-50ed-4dca-b078-338a8236e0f1.png">
Whenever I try to import something (P3D) into Blender 2.83 LTS, this message comes up. 
I have tried to reinstall this plugin, go on different computers, the same message always comes up. Anyone have a fix for it?

**Comment by wurunduk** [comment]
What kind of P3D model are you trying to load? This plugin is made specifically for the P3D models used by crashday.
If it is from crashday, may i have the model so i could take a look at it?

**Comment by dorathehonria** [comment]
I can't attach it here, but it is a debarinized P3D model I got from an Arma mod server. 
This may sound dumb but what is crashday

**Comment by wurunduk** [comment]
Crashday is a racing game. Event though in both crashday and arma models have a P3D extension, those models are actually in different formats. So you want be able to open P3D models from arma with this :(

I think this plugin may be what you need [ArmAToolbox](https://github.com/AlwarrenSidh/ArmAToolbox)
