### ISSUE TITLE
Keep getting this error on 3.6, 4.0 and 4.1

### ISSUE THREAD

**Issue by WD-40k** [wurunduk/blender-p3d-import-export#6]
![Untitled](https://github.com/wurunduk/blender-p3d-import-export/assets/167770351/b82fdce4-0262-48f5-a2b7-3980e468ee06)

**Comment by AdrixMED** [comment]
That's right. I have exactly the same thing. Version 4.2

**Comment by wurunduk** [comment]
> That's right. I have exactly the same thing. Version 4.2

Can you provide a model you are trying to open

**Comment by AdrixMED** [comment]
Hey, For example, this file.
[bear_zmb.zip](https://github.com/user-attachments/files/16828351/bear_zmb.zip)

**Comment by wurunduk** [comment]
> Hey, For example, this file. [bear_zmb.zip](https://github.com/user-attachments/files/16828351/bear_zmb.zip)

Looking at the file this is not a Crashday's p3d file format. This is some other game's p3d, presumably arma's.
This plugin is made specifically for Crashday's models.

**Comment by wurunduk** [comment]
I updated the plugin to show more understandable error when trying to import other game models
https://github.com/wurunduk/blender-p3d-import-export/commit/c05cedb83cecc234ef8bec8c0280938bb8c15112

**Comment by AdrixMED** [comment]
And now everything is clear ;) Thank you. That's right, it's an Army(DayZ) model. Would it be possible to include models from other games? For example, Arma?

**Comment by wurunduk** [comment]
> And now everything is clear ;) Thank you. That's right, it's an Army(DayZ) model. Would it be possible to include models from other games? For example, Arma?

These file formats are completely different even though they have the same extension letters. To support Arma models it pretty much means to create a new plugin and I have no plans to do so.

But you should look around, I'm pretty sure there are other plugins which work for arma models.
Maybe https://community.bistudio.com/wiki/Arma_Reforger:Enfusion_Blender_Tools:_P3D_Conversion
